### ISSUE TITLE
Read about PID 1 and the best practices for writing Dockerfiles.

### ISSUE THREAD

**Issue by kotto5** [kotto5/Inception#5]
docker のプロセスが 1 として立ち上がった時、何も設定しないと SIGTERM でプロセスを落とせないので困ることがある。

https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/

**Comment by kotto5** [comment]
だが、校舎Mac 環境で container の pid 1 に SIGTERM を送ってもプロセスを終了できた。

https://text.superbrothers.dev/200328-how-to-avoid-pid-1-problem-in-kubernetes/

docker exec _db ps aux

docker kill -s TERM _db

**Comment by kotto5** [comment]
## pid 1 がなぜ特別なのか?
> 簡単にいうと PID 1 のプロセスは Linux カーネルに特別扱いされていて、そのプロセス自身が明示的に送信されたシグナルをハンドリングしていない場合それを無視します。コンテナの場合、アプリケーションのプロセスが PID 1 で実行されることが多いため、アプリケーションが明示的にシグナルをハンドリングしていないとシグナルを送信しても無視されてしまい、コンテナに SIGTERM を送っても無視されて終了しないということが起こります。

1. pid 1 はSIGTERM を無視する
2. コンテナはアプリケーションのプロセスがPID1 で実行されることが多い
3. アプリケーションがSIGTERM を明示的にハンドリングしていないと無視されてしまう。

## 解決策
- アプリケーションがpid1 で実行されないようにする ( docker stop でシグナルの対象になるのはどのPID なのか? )
- アプリケーションに明示的にSIGTERMをハンドリングさせるようにする

## 疑問
- アプリケーションがpid1 で実行されないようにする ( docker stop でシグナルの対象になるのはどのPID なのか? )

**Comment by lim396** [comment]
pid 1問題の話の参考サイト

pid 1問題の概要
PID 1 問題というのは、コンテナを実行した際にアプリケーションのプロセスが PID 1（プロセス番号が1番）で実行されることで、コンテナに対して SIGTERM などのシグナルを送信してもコンテナ内のプロセスが正常に終了しないというものです。PID 1 のプロセスは Linux カーネルに特別扱いされていて、そのプロセス自身が明示的に送信されたシグナルをハンドリングしていない場合それを無視します。コンテナの場合、アプリケーションのプロセスが PID 1 で実行されることが多いため、アプリケーションが明示的にシグナルをハンドリングしていないとシグナルを送信しても無視されてしまい、コンテナに SIGTERM を送っても無視されて終了しないということが起こります。
引用元 https://text.superbrothers.dev/200328-how-to-avoid-pid-1-problem-in-kubernetes/

pid 1に関するサーバー正常終了の話
https://note.com/shift_tech/n/ndc63c45d9f97

docker doc
https://docs.docker.com/develop/develop-images/instructions/#entrypoint
https://docs.docker.com/engine/reference/commandline/stop/
