### ISSUE TITLE
NGINX with TLSv1.2 or TLSv1.3

### ISSUE THREAD

**Issue by kotto5** [kotto5/Inception#7]
- 採用する基準
- 実際にTLS を用いたnginx のセットアップ

**Comment by lim396** [comment]
nginxのconfの書き方
https://nginx.org/en/docs/http/configuring_https_servers.html
https://www.nginx.co.jp/blog/back-to-basics-web-traffic-encryption-with-ssl-tls-and-nginx/
https://nginx.org/en/docs/http/ngx_http_ssl_module.html

opensslのman
https://www.openssl.org/docs/manmaster/man1/openssl.html
鍵を作る時のコマンド↓
https://www.openssl.org/docs/manmaster/man1/openssl-x509.html

この辺参考にすればできそうです。

**Comment by kotto5** [comment]
[openssl req -new -key  secret.key で必要な引数を指定する方法](https://qiita.com/3244/items/780469306a3c3051c9fe#%E8%AD%98%E5%88%A5%E5%90%8D%E3%81%AE%E5%85%A5%E5%8A%9B%E3%82%92%E8%87%AA%E5%8B%95%E5%8C%96%E3%81%99%E3%82%8B)

[ req_distinguished_name ]
C = 2文字の国名
ST = 都道府県
L = 地域
O = 組織名
OU = 組織単位名
CN = コモンネーム
emailAddress = [test@email.address](mailto:test@email.address)

```
openssl req -new -key  server.key -subj /C=JP/ST=Tok
yo/L=Tokyo/O=42tokyo/OU=student/CN=kakiba.web/emailAddress=kakiba@student.42tokyo.jp"
```

**Comment by kotto5** [comment]
暗号化形式に指定はある?
rsa なんとか、とか

**Comment by kotto5** [comment]
openssl req -new は証明書を作成するコマンドではなく、証明書リクエストを作成するものだった
二個目のコマンドを採用して、証明書を作成します

```
openssl req -new -key /etc/nginx/secret.key -subj 
"/C=JP/ST=Tokyo/L=Tokyo/O=42tokyo/OU=student/CN=kakiba.web/emailAddress=kakiba@student.42tokyo.jp" > /etc/nginx/secret.crt
```
> 最初のコマンドは -new オプションを使用しています。これは新しい証明書署名リクエスト（CSR）を生成するためのもので、証明書自体は自己署名ではなく、証明書署名機関（Certificate Authority、CA）によって署名された証明書が必要です。したがって、このコマンドでは自己署名証明書は生成されません。


```
openssl req -x509 -nodes -days 30 -subj "/C=JP/ST=Tokyo/L=Tokyo/O=42tokyo/OU=student/CN=kakiba.web/emailAddress=kakiba@student.42tokyo.jp" -key /etc/nginx/secret.key -out /etc/nginx/secret.crt
```

> 2つ目のコマンドは -x509 オプションを使用しています。これは自己署名証明書を生成するためのもので、CAによる署名は必要ありません。-nodes オプションは秘密鍵のパスフレーズを設定しないことを意味し、-days 30 は証明書の有効期間を30日に設定しています。したがって、このコマンドでは自己署名証明書が生成されます。
